---
- name: create tower credential
  tower_credential:
    name: ec2-user
    description: AWS User
    organization: Default
    ssh_key_data: "{{key}}"
    kind: ssh
    state: present
    tower_config_file: "~/.tower_cli.cfg"
