---
- name: Configure the tower cli file
  template:
    src: tower_cli.cfg.j2
    dest: "~/.tower_cli.cfg"
    mode: 0600

- name: create tower credential
  tower_credential:
    name: ec2-user
    description: AWS User
    organization: Default
    ssh_key_data: ~/.ssh/"{{tower_GUID}}"key.pem
    state: present
    tower_config_file: "~/.tower_cli.cfg"
