---
- name: OpenStack facts
  os_server_facts:
    cloud: ospcloud
    server: 'frontend'
  register: openstack_result

- name: status check frontend server
  uri:
    url: "http://{{item.public_v4}}"
    return_content: yes
  with_items:
    - "{{ openstack_result.ansible_facts.openstack_servers }}"
  register: webcheck
  
- name: Fail if Status Code is not 200
  fail:
  when: item.status != 200
  with_items: 
  - "{{ webcheck.results }}"
  
  
