---
- name: OpenStack servers
  os_server_facts:
    cloud: ospcloud
    server: frontend
  register: facts_result

- name: check front end for string
  uri:
    url:  "http://{{item.public_v4}}"
    return_content: yes
  retries: 20
  delay: 1
  register: uri_result
  # until:  "'Ansible has done its job' in uri_result.content"
  
  failed_when: "'Ansible has done its job' not in uri_result.content"
  loop: "{{ facts_result.ansible_facts.openstack_servers }}"

  
