- hosts: jumpbox
  gather_facts: yes
  tasks:

  - name: openstack facts
    include_role:
      name: openstack_facts


- name: build_db_server
  hosts: appdbs
  gather_facts: true
  become: true
  tasks:

    - name: prep server
      include_role:
        name: prep-server

    - name: install postgress
      include_role:
        name: geerlingguy.postgresql


- name: build_app_server
  hosts: apps
  gather_facts: true
  become: true
  tasks:

    - name: prep server
      include_role:
        name: prep-server

    - name: install postgress
      include_role: 
        name: app-servers

- name: build_frontend_server
  hosts: frontends
  gather_facts: true
  become: true
  tasks:

    - name: prep server
      include_role:
        name: prep-server

    - name: install postgress
      include_role:
        name: geerlingguy.haproxy

    - name: Wait for ha proxy to connect to back ends
      wait_for:
        host: "{{ item.public_v4 }}"
        port: 80
        search_regex: Ansible
        timeout: 600
      delegate_to: "{{ inventory_hostname }}"
      loop: "{{ result.ansible_facts.openstack_servers }}"