- name: build_db_server
  hosts: appdbs
  gather_facts: true
  become: true
  tasks:

    - name: call prep-server role
      include_role:
        name: prep-server

    - name: call geerlingguy.postgresql role to install and configure postgres
      include_role:
        name: geerlingguy.postgresql


- name: build_app_server
  hosts: apps
  gather_facts: true
  become: true
  tasks:

    - name: call prep-server role
      include_role:
        name: prep-server

    - name: call app-servers role to install and configure tomcat
      include_role: 
        name: app-servers

- name: build_frontend_server
  hosts: frontends
  gather_facts: true
  become: true
  tasks:

    - name: call prep-server role
      include_role:
        name: prep-server

    - name: call geerlingguy.haproxy role to install and configure haproxy
      include_role:
        name: geerlingguy.haproxy
