- hosts: jumpbox
  gather_facts: yes
  tasks:

  - name: openstack facts
    include_role:
      name: openstack_facts

- name: localhost uri check on apps
  hosts: apps
  gather_facts: no
  tasks:

    - name: "wait for tomcat to come up"
      uri:
        url: "http://127.0.0.1:8080"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10


- hosts: jumpbox
  become: yes
  gather_facts: yes
  tasks:

  - name: smoketest openstack
    include_role:
      name: openstack_smoketest
  
  