# - hosts: jumpbox
#   gather_facts: yes
#   tasks:

#   - name: openstack facts
#     include_role:
#       name: openstack_facts

- name: localhost uri check on apps
  hosts: apps
  gather_facts: true
  become: true
  tasks:

    - name: localhost uri check to get the network rules working properlu
      uri:
        url: http://localhost
        return_content: yes

- hosts: jumpbox
  become: yes
  gather_facts: yes
  tasks:

  - name: smoketest openstack
    include_role:
      name: openstack_smoketest
  
  