- name: create tower credential for aws
  hosts: bastions
  gather_facts: true
  become: true
  tasks:

    - name: call tower-aws-credential role
      include_role:
        name: tower-aws-credential