---
- name: create bin directory
  file:
    path: /root/bin
    state: directory

- name: get script common.sh
  get_url:
    url: "{{ cf_url }}/scripts/common.sh"
    dest: /root/common.sh
    mode: 0755

- name: get script jq
  get_url: 
    url: "{{ cf_url }}/scripts/jq-linux64"
    dest: /root/bin/jq
    mode: 0755

- name: get script order_svc.sh
  get_url:
    url: "{{ cf_url }}/scripts/order_svc.sh"
    dest: /root/order_svc.sh
    mode: 0755

- name: copy credential template
  template:
    src: credential.rc.j2
    dest: /root/credential.rc
    mode: 0400

# Fix the existing shell scripts to reference jq command with bin/jq
- name: fix scripts
  shell: "sed -i 's/ jq/ bin\\/jq/g' {{ item }}"
  with_items:
    - /root/common.sh
    - /root/order_svc.sh

# Using this script will always deploy environments in the us-east-1 region.
- name: order service on opentlc
  shell: source /root/credential.rc; /root/order_svc.sh -y -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1
  args:
    chdir: /root

- name: Wait for mail
  pause:
    minutes: 10

- name: clean up credential file
  file:
    path: /root/credential.rc
    state: absent